In [16]:
import pandas as pd

def read_csv():
    names = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'modelyear', 'origin', 'carname']

    df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data", header=None, names=names)
    
    return df.shape # Update function to read the data into a data frame and return the shape

In [3]:
print(nums_gt5)

[6, 7, 8, 9, 10, 11, 12, 13, 14]


In [5]:
import numpy as np

# This creates our array
np_array = np.array([5, 10, 15, 20, 25, 30])
print("--0--")
print(np_array)

--0--
[ 5 10 15 20 25 30]


In [7]:
print(np.unique(np_array))

[ 5 10 15 20 25 30]


In [8]:
print(np.std(np_array))

8.539125638299666


In [9]:
print(np.max(np_array))

30


In [10]:
print(np_array ** 2)

[ 25 100 225 400 625 900]


In [11]:
print(np_array + np_array)

[10 20 30 40 50 60]


In [12]:
print(np.sum(np_array **2))

2275


In [14]:
print(np_array.shape)

(6,)
